🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👨🏿‍🏫📻📴✌🏼

Full error log:
Error:  asset 2022-9-14--22-36-43--0c7c235b-ea7b-4144-8443-fd4adff3380e/main.min.js 173 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
javascript modules 161 KiB
modules by path ./node_modules/ 150 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB 2 modules
2 modules
modules by path ./src/ 10.8 KiB 4 modules
asset modules 126 bytes
./assets/icons/dashed.png 42 bytes [built] [code generated]
./assets/icons/dotted.png 42 bytes [built] [code generated]
./assets/icons/solid.png 42 bytes [built] [code generated]
./package.json 814 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\art-tool-attribute-module\src\freehand-with-dashpattern-art-module.tsx
./src/freehand-with-dashpattern-art-module.tsx 9:13-39
[tsl] ERROR in C:\Users\me\work\collboard\art-tool-attribute-module\src\freehand-with-dashpattern-art-module.tsx(9,14)
TS2515: Non-abstract class 'FreehandWithDashpatternArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.
@ ./src/00-index.ts 4:0-49

ERROR in C:\Users\me\work\collboard\art-tool-attribute-module\src\freehand-with-dashpattern-art-module.tsx
./src/freehand-with-dashpattern-art-module.tsx 9:13-39
[tsl] ERROR in C:\Users\me\work\collboard\art-tool-attribute-module\src\freehand-with-dashpattern-art-module.tsx(9,14)
TS2515: Non-abstract class 'FreehandWithDashpatternArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.
@ ./src/00-index.ts 4:0-49

webpack 5.35.1 compiled with 2 errors in 6406 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\art-tool-attribute-module\node_modules\webpack\lib\Watching.js:201:28)